# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PIN_GPIO": "raspberrypi_growlight.ipynb",
         "TIMEZONE": "raspberrypi_growlight.ipynb",
         "Schedule": "raspberrypi_growlight.ipynb",
         "SunlightSchedule": "raspberrypi_growlight.ipynb",
         "LowellSunlightSchedule": "raspberrypi_growlight.ipynb",
         "INTERVAL": "raspberrypi_growlight.ipynb",
         "GrowlightScheduler": "raspberrypi_growlight.ipynb",
         "app": "raspberrypi_growlight.ipynb",
         "schedule": "raspberrypi_growlight.ipynb",
         "growlight": "raspberrypi_growlight.ipynb",
         "scheduler_growlight": "raspberrypi_growlight.ipynb",
         "ON": "raspberrypi_growlight.ipynb",
         "OFF": "raspberrypi_growlight.ipynb",
         "START": "raspberrypi_growlight.ipynb",
         "PAUSE": "raspberrypi_growlight.ipynb",
         "SHUTDOWN": "raspberrypi_growlight.ipynb",
         "Growlight": "raspberrypi_growlight.ipynb",
         "STATUS": "raspberrypi_growlight.ipynb"}

modules = ["raspberrypi_growlight.py"]

doc_url = "https://justinblaber.github.io/raspberrypi_growlight/"

git_url = "https://github.com/justinblaber/raspberrypi_growlight/tree/{branch}/"

def custom_doc_links(name): return None
